from tkinter import *
import random
from typing import NewType

# Create window object
app = Tk()
app.title('Hydra Virus')
app.geometry('500x500')
app.resizable(0, 0)

# Draw Hydra
hydraSpacing = Label(app, text=' ', font=('bold', 14), pady=10)
hydraSpacing.config(anchor=CENTER)
hydraSpacing.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()
hydraSerpant = Label(app, text='-----------------------------------------------------------------------------------------------', font=('bold', 5), pady=0)
hydraSerpant.config(anchor=CENTER)
hydraSerpant.pack()

# Display message
hydraMessage = Label(app, text='Cut off a head, two or more will take its place.', font=('bold', 14), pady=40)
hydraMessage.config(anchor=CENTER)
hydraMessage.pack()

# Function to open a new window  
def openNewWindow(): 
    # Toplevel object which will be treated as a new window 
    newAPP = Tk() 
    newAPP.title("Hydra Virus") 
    newAPP.geometry("500x500")
    newAPP.resizable(0, 0)

    # Draw Head
    newHead = Label(newAPP, text='---------------------------------------------------------', font=('bold', 14), pady=20)
    newHead.config(anchor=CENTER)
    newHead.pack()

    # Display message
    newHead = Label(app, text='Cut off a head, two or more will take its place.', font=('bold', 14), pady=40)
    newHead.config(anchor=CENTER)
    newHead.pack()

    newAPP.protocol("WM_DELETE_WINDOW", closeWindow)

# Get number of new heads
def getHeads():
    return random.randint(2, 5)

def closeWindow():
    for i in range(getHeads()):
        openNewWindow()

# app.protocol("WM_DELETE_WINDOW", closeWindow)

# Start program
app.mainloop()